import Colors from './colors';

export enum EBackgroundAvatar {
  AVATAR_BACKGROUND_1 = 'AVATAR_BACKGROUND_1',
  AVATAR_BACKGROUND_2 = 'AVATAR_BACKGROUND_2',
  AVATAR_BACKGROUND_3 = 'AVATAR_BACKGROUND_3',
  AVATAR_BACKGROUND_4 = 'AVATAR_BACKGROUND_4',
  AVATAR_BACKGROUND_5 = 'AVATAR_BACKGROUND_5',
  AVATAR_BACKGROUND_6 = 'AVATAR_BACKGROUND_6',
  AVATAR_BACKGROUND_7 = 'AVATAR_BACKGROUND_7',
  AVATAR_BACKGROUND_8 = 'AVATAR_BACKGROUND_8',
  AVATAR_BACKGROUND_9 = 'AVATAR_BACKGROUND_9',
  AVATAR_BACKGROUND_10 = 'AVATAR_BACKGROUND_10',
  AVATAR_BACKGROUND_11 = 'AVATAR_BACKGROUND_11',
  AVATAR_BACKGROUND_12 = 'AVATAR_BACKGROUND_12',
}

export const BACKGROUND_AVATAR_COLORS = {
  dark: {
    [EBackgroundAvatar.AVATAR_BACKGROUND_1]: Colors.ng30,
    [EBackgroundAvatar.AVATAR_BACKGROUND_2]: Colors.ng100,
    [EBackgroundAvatar.AVATAR_BACKGROUND_3]: Colors.ng95,
    [EBackgroundAvatar.AVATAR_BACKGROUND_4]: Colors.ng92,
    [EBackgroundAvatar.AVATAR_BACKGROUND_5]: Colors.ng90,
  },
  light: {
    [EBackgroundAvatar.AVATAR_BACKGROUND_1]: Colors.ng30,
    [EBackgroundAvatar.AVATAR_BACKGROUND_2]: Colors.ng100,
    [EBackgroundAvatar.AVATAR_BACKGROUND_3]: Colors.ng95,
    [EBackgroundAvatar.AVATAR_BACKGROUND_4]: Colors.ng92,
    [EBackgroundAvatar.AVATAR_BACKGROUND_5]: Colors.ng90,
  },
};
