import Colors from './colors';

export enum EText {
  'TEXT' = 'TEXT',
  'TEXT_SUBTLE' = 'TEXT_SUBTLE',
  'TEXT_SUBTLEST' = 'TEXT_SUBTLEST',
  'TEXT_DISABLED' = 'TEXT_DISABLED',
  'TEXT_ON_INVERSE' = 'TEXT_ON_INVERSE',
  'TEXT_ON_INVERSE_SUBTLE' = 'TEXT_ON_INVERSE_SUBTLE',
  'TEXT_ON_COLOR' = 'TEXT_ON_COLOR',
  'TEXT_BRAND' = 'TEXT_BRAND',
  'TEXT_INFORMATION' = 'TEXT_INFORMATION',
  'TEXT_SUCCESS' = 'TEXT_SUCCESS',
  'TEXT_ERROR' = 'TEXT_ERROR',
  'TEXT_ON_INVERSE_CONSTANT' = 'TEXT_ON_INVERSE_CONSTANT',
  'TEXT_WARNING' = 'TEXT_WARNING',
  'TEXT_LABEL_1' = 'TEXT_LABEL_1',
  'TEXT_LABEL_2' = 'TEXT_LABEL_2',
}

export const TEXT_COLOR = {
  dark: {
    [EText.TEXT]: Colors.ng1,
    [EText.TEXT_SUBTLE]: Colors.ng40,
    [EText.TEXT_SUBTLEST]: Colors.ng60,
    [EText.TEXT_DISABLED]: Colors.white_a25,
    [EText.TEXT_ON_INVERSE]: Colors.ng100,
    [EText.TEXT_ON_INVERSE_SUBTLE]: Colors.ng60,
    [EText.TEXT_ON_INVERSE_CONSTANT]: Colors.ng100,
    [EText.TEXT_ON_COLOR]: Colors.ng1,
    [EText.TEXT_BRAND]: Colors.y40,
    [EText.TEXT_INFORMATION]: Colors.b30,
    [EText.TEXT_SUCCESS]: Colors.gr60,
    [EText.TEXT_ERROR]: Colors.r50,
    [EText.TEXT_WARNING]: Colors.or50,
    [EText.TEXT_LABEL_1]: Colors.br60,
    [EText.TEXT_LABEL_2]: Colors.ng40,
  },
  light: {
    [EText.TEXT]: Colors.ng100,
    [EText.TEXT_SUBTLE]: Colors.ng60,
    [EText.TEXT_SUBTLEST]: Colors.ng40,
    [EText.TEXT_DISABLED]: Colors.black_a25,
    [EText.TEXT_ON_INVERSE]: Colors.ng1,
    [EText.TEXT_ON_INVERSE_SUBTLE]: Colors.ng40,
    [EText.TEXT_ON_INVERSE_CONSTANT]: Colors.ng100,
    [EText.TEXT_ON_COLOR]: Colors.ng1,
    [EText.TEXT_BRAND]: Colors.y40,
    [EText.TEXT_INFORMATION]: Colors.b40,
    [EText.TEXT_SUCCESS]: Colors.gr70,
    [EText.TEXT_ERROR]: Colors.r50,
    [EText.TEXT_WARNING]: Colors.or60,
    [EText.TEXT_LABEL_1]: Colors.br60,
    [EText.TEXT_LABEL_2]: Colors.ng60,
  },
};
